<template><div><h1 class="text-3xl font-bold">Réglages</h1><p class="mt-2 text-[var(--muted)]">Valeurs éditables sans exposer les secrets d’environnement.</p><form class="card mt-8 max-w-2xl space-y-4" @submit.prevent="save"><label v-for="item in items" :key="item.key" class="block text-xs font-semibold">{{ labels[item.key]||item.key }}<input v-model="item.value" class="field mt-2"/></label><p class="text-xs leading-5 text-[var(--muted)]">Les secrets, clés S3 et clés API restent exclusivement dans les variables d’environnement.</p><p v-if="notice" class="text-sm text-emerald-700">{{ notice }}</p><button class="btn-primary">Enregistrer</button></form>
  <form class="card mt-8 max-w-2xl space-y-4" @submit.prevent="changePassword"><h2 class="text-xl font-bold">Changer mon mot de passe</h2><label class="block text-xs font-semibold">Mot de passe actuel<input v-model="pwd.currentPassword" type="password" class="field mt-2" autocomplete="current-password" required/></label><label class="block text-xs font-semibold">Nouveau mot de passe<input v-model="pwd.newPassword" type="password" class="field mt-2" minlength="8" autocomplete="new-password" required/></label><label class="block text-xs font-semibold">Confirmer le nouveau mot de passe<input v-model="pwd.confirmPassword" type="password" class="field mt-2" minlength="8" autocomplete="new-password" required/></label><p v-if="pwdNotice" class="text-sm" :class="pwdOk?'text-emerald-700':'text-red-700'">{{ pwdNotice }}</p><button class="btn-primary" :disabled="pwdPending">Mettre à jour le mot de passe</button></form>
</div></template>
<script setup lang="ts">definePageMeta({middleware:'admin',layout:'admin',i18n:{locales:['fr']}});useSeoMeta({title:'Réglages',robots:'noindex,nofollow'});const defaults=[{key:'default_gate_fields',value:'firstName,email,phone,domain'},{key:'lead_notification_email',value:'contact@novatrixai.com'}];const {data}=await useFetch<any>('/api/admin/settings',{default:()=>({items:[]})});const items=ref(data.value.items.length?data.value.items:defaults),notice=ref(''),labels:Record<string,string>={default_gate_fields:'Champs du formulaire ressource',lead_notification_email:'Email de notification'};async function save(){await $fetch('/api/admin/settings',{method:'PUT',body:{items:items.value}});notice.value='Réglages enregistrés.'}
const pwd=reactive({currentPassword:'',newPassword:'',confirmPassword:''}),pwdNotice=ref(''),pwdOk=ref(false),pwdPending=ref(false)
async function changePassword(){
  if(pwd.newPassword!==pwd.confirmPassword){pwdOk.value=false;pwdNotice.value='Les deux mots de passe ne correspondent pas.';return}
  pwdPending.value=true;pwdNotice.value=''
  try{await $fetch('/api/admin/change-password',{method:'POST',body:{currentPassword:pwd.currentPassword,newPassword:pwd.newPassword}});pwdOk.value=true;pwdNotice.value='Mot de passe mis à jour.';Object.assign(pwd,{currentPassword:'',newPassword:'',confirmPassword:''})}
  catch(err:any){pwdOk.value=false;pwdNotice.value=err?.data?.statusMessage||'Échec de la mise à jour'}
  finally{pwdPending.value=false}
}
</script>
