<template>
  <div class="hero-video">
    <!-- Sur mobile et en mouvement réduit, seule l'affiche Cloudinary est chargée : la vidéo
         n'est même pas montée, donc aucun octet de vidéo n'est téléchargé. -->
    <img
      v-if="!playVideo"
      :src="asset.poster"
      alt=""
      aria-hidden="true"
      class="hero-video-media"
      loading="eager"
      fetchpriority="high"
    >
    <video
      v-else
      :src="asset.src"
      :poster="asset.poster"
      class="hero-video-media"
      autoplay
      muted
      loop
      playsinline
      preload="metadata"
      aria-hidden="true"
      tabindex="-1"
    />
    <span class="hero-video-veil" aria-hidden="true"/>
    <span class="hero-video-badge">{{ t.badge }}</span>
  </div>
</template>

<script setup lang="ts">
import videoAssets from '~/shared/video-lab-assets.json'

// Extrait du Video Lab : la même vidéo générée par IA sert de démonstration en page d'accueil.
// Le badge le dit explicitement, pour que personne ne prenne la séquence pour un tournage réel.
const asset = videoAssets['fondateur-cinematique'] as { src: string; poster: string }

const { locale } = useI18n()
const t = computed(() => locale.value === 'en'
  ? { badge: 'Generated by AI' }
  : { badge: 'Générée par IA' })

// La vidéo ne démarre que sur grand écran et si l'utilisateur n'a pas demandé moins d'animations.
// Évalué côté client uniquement (pas de window au rendu serveur), d'où la valeur initiale false :
// l'affiche s'affiche d'abord, la vidéo prend le relais après montage si les conditions sont réunies.
const playVideo = ref(false)
let motionQuery: MediaQueryList | null = null
let widthQuery: MediaQueryList | null = null

function syncPlayback() {
  playVideo.value = !!widthQuery?.matches && !motionQuery?.matches
}

onMounted(() => {
  motionQuery = window.matchMedia('(prefers-reduced-motion: reduce)')
  widthQuery = window.matchMedia('(min-width: 1024px)')
  motionQuery.addEventListener('change', syncPlayback)
  widthQuery.addEventListener('change', syncPlayback)
  syncPlayback()
})
onBeforeUnmount(() => {
  motionQuery?.removeEventListener('change', syncPlayback)
  widthQuery?.removeEventListener('change', syncPlayback)
})
</script>

<style scoped>
.hero-video {
  position: relative;
  overflow: hidden;
  border-radius: 1.25rem;
  border: 1px solid rgba(255, 255, 255, .16);
  background: linear-gradient(135deg, #2a0f5c, #160630 55%, #0b0318);
  box-shadow: 0 24px 70px rgba(0, 0, 0, .45);
  /* Format plus ramassé sur mobile : en 16/10 la vidéo dépassait sous la ligne de
     flottaison et se retrouvait coupée. Le ratio large reprend à partir du desktop, où
     elle occupe la colonne de droite.
     La hauteur est exprimée en svh (hauteur réellement disponible, barre d'URL comprise)
     et non en vh, qui ignore cette barre et laissait le CTA déborder de quelques pixels
     sur un écran court. */
  aspect-ratio: 16 / 9;
  max-height: 22svh;
}
@media (min-width: 1024px) {
  .hero-video {
    aspect-ratio: 16 / 10;
    max-height: none;
  }
}
.hero-video-media {
  display: block;
  width: 100%;
  height: 100%;
  object-fit: cover;
}
/* Voile violet : la vidéo reste lisible comme image, sans concurrencer le titre à sa gauche. */
.hero-video-veil {
  position: absolute;
  inset: 0;
  pointer-events: none;
  background: linear-gradient(115deg, rgba(28, 0, 56, .55) 0%, rgba(28, 0, 56, .12) 45%, transparent 100%);
}
.hero-video-badge {
  position: absolute;
  left: .85rem;
  bottom: .85rem;
  border-radius: 999px;
  background: rgba(11, 3, 24, .62);
  backdrop-filter: blur(6px);
  -webkit-backdrop-filter: blur(6px);
  border: 1px solid rgba(255, 255, 255, .18);
  padding: .3rem .7rem;
  font-size: .65rem;
  font-weight: 700;
  letter-spacing: .06em;
  text-transform: uppercase;
  color: rgba(255, 255, 255, .85);
}
</style>
