<template>
  <div ref="revealRoot">
    <PageHero :kicker="kicker" :description="description"><slot name="title">{{ title }}</slot><template #actions><button type="button" class="btn-primary" @click="openCalendly">{{ $t('header.bookCall') }} <ArrowRight class="h-4 w-4"/></button><NuxtLink to="#systeme" class="btn-secondary">{{ t.viewSystem }}</NuxtLink></template></PageHero>
    <section id="systeme" class="section-pad"><div class="container-shell grid items-start gap-12 lg:grid-cols-2"><div class="reveal-left"><SectionHeading :kicker="t.systemKicker">{{ systemTitle }}</SectionHeading><p class="mt-6 text-lg leading-8 text-[var(--muted)]">{{ systemText }}</p><div v-if="guard" class="mt-7 rounded-xl border border-amber-500/20 bg-amber-500/5 p-5 text-sm leading-6 text-[var(--muted)]"><ShieldCheck class="mb-3 h-5 w-5 text-amber-600"/>{{ guard }}</div></div><slot name="visual"><div class="card reveal-right overflow-hidden !p-0"><img v-if="illustration" :src="illustration" :alt="systemTitle" width="720" height="405" class="aspect-video h-auto w-full object-cover" loading="lazy" decoding="async"/><div class="p-8"><div v-for="(item,i) in modules" :key="item" class="reveal flex items-center gap-4 border-b py-4 last:border-0" :data-reveal-delay="i*70"><span class="grid h-9 w-9 place-items-center rounded-lg bg-violet-600/10 font-mono text-xs font-bold text-violet-700 dark:text-violet-300">{{ String(i+1).padStart(2,'0') }}</span><p class="font-semibold">{{ item }}</p><Check class="ml-auto h-4 w-4 text-[var(--teal)]"/></div></div></div></slot></div></section>
    <section class="section-pad border-y bg-[var(--surface)]"><div class="container-shell"><div class="reveal"><SectionHeading :kicker="t.capabilitiesKicker" center>{{ capabilitiesTitle }}</SectionHeading></div><div class="mt-12 grid gap-5 md:grid-cols-3"><div v-for="(item,i) in capabilities" :key="item.title" class="card card-hover reveal-scale" :data-reveal-delay="i*120"><component :is="item.icon" class="h-6 w-6 text-violet-600"/><h3 class="mt-4 text-lg font-bold">{{ item.title }}</h3><p class="mt-2 text-sm leading-6 text-[var(--muted)]">{{ item.text }}</p></div></div></div></section>
    <section class="section-pad"><div class="container-shell"><div class="reveal"><SectionHeading :kicker="t.deliveryKicker" center :description="t.deliveryDescription">{{ t.deliveryTitle1 }} <span class="text-gradient">{{ t.deliveryTitle2 }}</span></SectionHeading></div><div class="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4"><div v-for="(item,i) in steps" :key="item.step" class="card card-hover reveal" :data-reveal-delay="i*100"><span class="font-heading text-4xl font-bold text-violet-600/15">{{ item.step }}</span><h3 class="mt-4 font-bold">{{ item.title }}</h3><p class="mt-2 text-sm leading-6 text-[var(--muted)]">{{ item.text }}</p><p v-if="item.outcome" class="mt-4 flex items-start gap-2 border-t pt-4 text-xs font-semibold text-[var(--teal)]"><Check class="mt-0.5 h-3.5 w-3.5 shrink-0"/>{{ t.outcomeLabel }} {{ item.outcome }}</p></div></div></div></section>
    <section v-if="$slots.proof" class="section-pad border-y bg-[var(--surface)]"><div class="container-shell"><div class="reveal mx-auto max-w-2xl text-center"><SectionHeading :kicker="t.proofKicker" center>{{ t.proofTitle1 }} <span class="text-gradient">{{ t.proofTitle2 }}</span></SectionHeading></div><div class="reveal mx-auto mt-12 max-w-3xl"><slot name="proof"/></div></div></section>
    <section v-if="faqs?.length" class="section-pad"><div class="container-shell grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div class="reveal-left"><SectionHeading :kicker="t.faqKicker">{{ t.faqTitle1 }} <span class="text-gradient">{{ t.faqTitle2 }}</span></SectionHeading></div><div class="reveal-right"><FaqAccordion :items="faqs"/></div></div></section>
    <CtaBand :title="ctaTitle"/>
  </div>
</template>
<script setup lang="ts">
import { ArrowRight, Check, ShieldCheck } from 'lucide-vue-next'
import type { Component } from 'vue'
defineProps<{kicker:string;illustration?:string;title:string;description:string;systemTitle:string;systemText:string;guard?:string;modules:string[];capabilitiesTitle:string;capabilities:{icon:Component;title:string;text:string}[];steps:{step:string;title:string;text:string;outcome?:string}[];faqs?:{question:string;answer:string}[];ctaTitle:string}>()
const { locale } = useI18n()
const { openCalendly } = useCalendly()
const revealRoot = useScrollReveal()
const t = computed(() => locale.value === 'en' ? {
  viewSystem:'View the system', systemKicker:'the system', capabilitiesKicker:'capabilities', deliveryKicker:'delivery path', deliveryDescription:'Each phase has an explicit output and a review point.', deliveryTitle1:'A progression with', deliveryTitle2:'visible checkpoints.', outcomeLabel:'Output:', proofKicker:'real result', proofTitle1:'A result obtained by a', proofTitle2:'client system.', faqKicker:'frequently asked questions', faqTitle1:'Clear before the', faqTitle2:'audit.',
} : {
  viewSystem:'Voir le système', systemKicker:'le système', capabilitiesKicker:'capacités', deliveryKicker:'parcours de livraison', deliveryDescription:'Chaque phase produit un livrable explicite et un point de revue.', deliveryTitle1:'Une progression avec', deliveryTitle2:'des jalons visibles.', outcomeLabel:'Livrable :', proofKicker:'résultat réel', proofTitle1:'Un résultat obtenu par un', proofTitle2:'système client.', faqKicker:'questions fréquentes', faqTitle1:'Clair avant', faqTitle2:'l’audit.',
})
</script>
