<template><div ref="revealRoot"><PageHero kicker="novatrixai" description="Agence de systèmes IA basée à Cotonou, au service d’entreprises francophones et internationales.">Nous ne vendons pas des tâches.<br><span class="text-gradient">Nous relions des résultats.</span></PageHero>
  <section class="section-pad"><div class="container-shell grid gap-12 lg:grid-cols-2"><div class="reveal-left"><SectionHeading kicker="notre conviction">Le problème est rarement la pièce. C’est <span class="text-gradient">l’absence de système.</span></SectionHeading></div><div class="reveal-right space-y-5 text-lg leading-8 text-[var(--muted)]"><p>Une publicité performante ne sert à rien si la page ne convertit pas. Une page qui convertit ne sert à rien si les leads ne sont pas relancés.</p><p>NovatrixAI prend la responsabilité de la chaîne : architecture, construction, connexions, tests et évolution.</p></div></div></section>
  <section class="section-pad border-y bg-[var(--surface)]"><div class="container-shell"><div class="reveal"><SectionHeading kicker="façon de travailler" center>Des standards simples. <span class="text-gradient">Tenus jusqu’au bout.</span></SectionHeading></div><div class="mt-12 grid gap-5 md:grid-cols-3"><div v-for="(item,i) in values" :key="item.title" class="card card-hover glass-sheen reveal-scale" :data-reveal-delay="i*90"><component :is="item.icon" class="h-6 w-6 text-violet-600"/><h3 class="mt-4 text-lg font-bold">{{ item.title }}</h3><p class="mt-2 text-sm leading-6 text-[var(--muted)]">{{ item.text }}</p></div></div></div></section><CtaBand/></div></template>
<script setup lang="ts">
import { BadgeCheck,BrainCircuit,FileText,Focus,Route,TimerReset } from 'lucide-vue-next'
usePageSeo('À propos', 'Découvrez NovatrixAI, agence de systèmes IA basée à Cotonou : mission, conviction et standards de travail.')
const revealRoot=useScrollReveal()
const values=[{icon:BadgeCheck,title:'Responsabilité du résultat',text:'Nous sommes responsables de toute la chaîne, pas d’une étape.'},{icon:BrainCircuit,title:'Systèmes, pas bricolage',text:'Fiable, documenté, maintenable et évolutif.'},{icon:Focus,title:'Business d’abord',text:'Le résultat dicte l’outil, jamais l’inverse.'},{icon:FileText,title:'Clarté',text:'Le client comprend ce qui existe et pourquoi.'},{icon:TimerReset,title:'Délais respectés',text:'Un engagement pris reste un engagement tenu.'},{icon:Route,title:'Progression testée',text:'Aucune phase ne démarre sur un maillon non validé.'}]
</script>
