<template><div><PageHero kicker="contact" description="Expliquez le résultat que vous cherchez. Nous vous aiderons à cartographier la chaîne nécessaire.">Le prochain système commence par <span class="text-gradient">une conversation.</span></PageHero>
  <section class="section-pad"><div class="container-shell grid gap-10 lg:grid-cols-2"><div class="card !p-7 sm:!p-9"><h2 class="text-2xl font-bold">Décrivez votre contexte.</h2><form class="mt-7 grid gap-4 sm:grid-cols-2" @submit.prevent="submit"><label class="text-xs font-semibold">Prénom *<input v-model.trim="form.firstName" class="field mt-2" required/></label><label class="text-xs font-semibold">Email *<input v-model.trim="form.email" class="field mt-2" type="email" required/></label><label class="text-xs font-semibold">Téléphone *<input v-model.trim="form.phone" class="field mt-2" type="tel" required/></label><label class="text-xs font-semibold">Entreprise *<input v-model.trim="form.domain" class="field mt-2" required/></label><label class="col-span-full text-xs font-semibold">Quel résultat cherchez-vous ?<textarea v-model.trim="form.message" class="field mt-2 min-h-32 py-3"/></label><input v-model="form.website" tabindex="-1" class="absolute -left-[9999px]" autocomplete="off"/><label class="col-span-full flex items-start gap-3 text-xs leading-5 text-[var(--muted)]"><input v-model="form.consent" class="mt-1 accent-violet-600" type="checkbox" required/>J’accepte d’être recontacté par NovatrixAI. <NuxtLink to="/confidentialite" class="text-violet-700 underline">Politique de confidentialité</NuxtLink></label><p v-if="feedback" class="col-span-full rounded-xl p-3 text-sm" :class="success?'bg-emerald-500/10 text-emerald-700':'bg-red-500/10 text-red-700'">{{ feedback }}</p><button class="btn-primary col-span-full" :disabled="pending"><LoaderCircle v-if="pending" class="h-4 w-4 animate-spin"/>Envoyer la demande</button></form></div>
    <div><div class="card !p-7"><p class="kicker">appel de découverte</p><h2 class="mt-4 text-2xl font-bold">Choisissez directement un créneau.</h2><p class="mt-3 text-sm leading-6 text-[var(--muted)]">Un échange court pour comprendre l’existant et décider si nous sommes le bon partenaire.</p><a :href="calendarUrl" target="_blank" rel="noopener noreferrer" class="btn-primary mt-6">Ouvrir l’agenda <ExternalLink class="h-4 w-4"/></a></div><a :href="whatsappUrl" target="_blank" rel="noopener noreferrer" class="mt-5 flex items-center gap-4 rounded-2xl border bg-[#075E54] p-6 text-white transition hover:-translate-y-1"><MessageCircle class="h-7 w-7"/><span><strong class="block">Écrire sur WhatsApp</strong><small class="text-white/65">Pour une question rapide avant l’appel.</small></span></a></div></div></section></div></template>
<script setup lang="ts">
import { ExternalLink,LoaderCircle,MessageCircle } from 'lucide-vue-next'
usePageSeo('Contact et appel de découverte','Contactez NovatrixAI ou réservez un appel de découverte pour votre système IA.')
const config=useRuntimeConfig(),calendarUrl=config.public.calendarUrl,whatsappUrl=config.public.whatsappUrl
const form=reactive({firstName:'',email:'',phone:'',domain:'',message:'',consent:false,website:'',source:'contact'}),pending=ref(false),feedback=ref(''),success=ref(false)
async function submit(){pending.value=true;feedback.value='';try{await $fetch('/api/leads',{method:'POST',body:form});success.value=true;feedback.value='Demande reçue. Nous revenons vers vous rapidement.'}catch(e:any){success.value=false;feedback.value=e?.data?.statusMessage||'Envoi impossible. Réessayez dans un instant.'}finally{pending.value=false}}
</script>
