import type { PublicArticle, PublicResource } from './types'

export const demoResources: PublicResource[] = [
  { title:'Checklist : auditer votre chaîne d’acquisition',slug:'checklist-audit-acquisition',description:'Repérez les ruptures entre campagnes, tunnel, CRM, relances et closing avant qu’elles ne coûtent des clients.',type:'pdf',sector:'Acquisition',fileKey:'demo/checklist-acquisition.pdf',published:true,leadCount:0 },
  { title:'Cartographie des agents IA de pilotage',slug:'cartographie-agents-pilotage',description:'Un canevas pour choisir les domaines à déléguer, les validations humaines et les outils à connecter.',type:'template',sector:'Pilotage IA',fileKey:'demo/cartographie-agents.pdf',published:true,leadCount:0 },
  { title:'Guide : cadrer une application métier',slug:'guide-cadrage-application-metier',description:'Les décisions à prendre avant de développer une application web ou mobile réellement utile.',type:'pdf',sector:'Web & apps',fileKey:'demo/guide-cadrage-app.pdf',published:true,leadCount:0 },
]

export const demoArticles: PublicArticle[] = [
  { title:'Pourquoi votre acquisition se casse entre deux outils',slug:'acquisition-cassee-entre-outils',excerpt:'Le vrai coût n’est pas toujours la campagne. Il se cache souvent dans le passage du lead au CRM, puis du CRM à la relance.',body:'## Le maillon invisible\n\nUne campagne peut produire des contacts sans produire de clients. La rupture arrive quand chaque outil fonctionne seul.\n\n## Cartographier avant d’automatiser\n\nSuivez un lead réel, du premier clic jusqu’à la décision. Chaque ressaisie, attente ou statut flou indique un maillon à reconstruire.\n\n## Relier le résultat\n\nUn système d’acquisition complet aligne les créatifs, les campagnes, le tunnel, le CRM, les relances et le closing autour d’une même donnée.',category:'Acquisition',tags:['CRM','Automatisation'],readingTime:4,status:'published',source:'manual',publishedAt:'2026-06-24T08:00:00.000Z' },
  { title:'Agents IA : où garder une validation humaine',slug:'agents-ia-validation-humaine',excerpt:'L’autonomie utile ne consiste pas à tout laisser faire. Elle place la validation humaine exactement là où l’enjeu l’exige.',body:'## Autonomie ne veut pas dire abandon\n\nUn agent peut préparer, analyser et exécuter. Sur les sujets juridiques, fiscaux ou financiers, une validation humaine doit rester explicite.\n\n## Trois niveaux simples\n\nObservation, proposition, puis exécution autorisée. Cette graduation rend le système fiable sans étouffer le gain de temps.',category:'Pilotage IA',tags:['Agents IA','Gouvernance'],readingTime:3,status:'published',source:'automation',publishedAt:'2026-06-20T08:00:00.000Z' },
  { title:'Le bon périmètre pour une première application métier',slug:'perimetre-premiere-application-metier',excerpt:'Commencer petit ne signifie pas construire au rabais. Cela signifie livrer une boucle métier complète et mesurable.',body:'## Une boucle complète\n\nChoisissez un utilisateur, une décision et un résultat. La première version doit couvrir cette boucle de bout en bout.\n\n## Ce qui attendra\n\nLes variantes rares et les raffinements visuels viennent après la validation du flux principal.',category:'Produit',tags:['Application','Cadrage'],readingTime:3,status:'published',source:'manual',publishedAt:'2026-06-16T08:00:00.000Z' },
]
