import type { PublicArticle, PublicProject, PublicResource, PublicTestimonial } from './types'

export const demoResources: PublicResource[] = [
  { title:'Checklist : auditer votre chaîne d’acquisition',titleEn:'Checklist: auditing your acquisition chain',slug:'checklist-audit-acquisition',description:'Repérez les ruptures entre campagnes, tunnel, CRM, relances et closing avant qu’elles ne coûtent des clients.',descriptionEn:'Spot the breaks between campaigns, funnel, CRM, follow-ups and closing before they cost you clients.',type:'pdf',sector:'Acquisition',sectorEn:'Acquisition',fileKey:'demo/checklist-acquisition.pdf',published:true,leadCount:0 },
  { title:'Cartographie des agents IA de pilotage',titleEn:'Mapping your AI piloting agents',slug:'cartographie-agents-pilotage',description:'Un canevas pour choisir les domaines à déléguer, les validations humaines et les outils à connecter.',descriptionEn:'A canvas to choose which domains to delegate, which human validations to keep, and which tools to connect.',type:'template',sector:'Pilotage IA',sectorEn:'AI Piloting',fileKey:'demo/cartographie-agents.pdf',published:true,leadCount:0 },
  { title:'Guide : cadrer une application métier',titleEn:'Guide: scoping a business application',slug:'guide-cadrage-application-metier',description:'Les décisions à prendre avant de développer une application web ou mobile réellement utile.',descriptionEn:'The decisions to make before developing a web or mobile application that’s actually useful.',type:'pdf',sector:'Web & apps',sectorEn:'Web & Apps',fileKey:'demo/guide-cadrage-app.pdf',published:true,leadCount:0 },
]

// Sous-ensemble de secours (hors ligne / DB indisponible) : projets réels tirés du profil ComeUp de NovatrixAI.
// L'ensemble complet (31 réalisations, traductions incluses) vit en base — voir scripts/seed-comeup.mjs et scripts/seed-en-projects.mjs.
export const demoProjects: PublicProject[] = [
  { title:'Jeefox, moteur de recherche intelligent',titleEn:'Jeefox, an intelligent search engine',slug:'jeefox-moteur-de-recherche-intelligent',category:'Web & applications',categoryEn:'Web & Apps',summary:'Moteur de recherche intelligent conçu pour indexer et retrouver l’information pertinente rapidement.',summaryEn:'Intelligent search engine designed to index and retrieve relevant information quickly.',tools:[],status:'published',featured:true,source:'comeup' },
  { title:'Site vitrine de l’agence WingoAI',titleEn:'WingoAI Agency Showcase Website',slug:'site-vitrine-agence-wingoai',category:'Web & applications',categoryEn:'Web & Apps',summary:'Site vitrine développé pour présenter l’activité et les services de l’agence WingoAI.',summaryEn:'Showcase website built to present WingoAI agency’s activity and services.',tools:[],status:'published',featured:true,source:'comeup' },
  { title:'Relance automatique des paniers abandonnés',titleEn:'Automatic abandoned cart recovery',slug:'relance-paniers-abandonnes-shopify-twilio',category:'Acquisition',categoryEn:'Acquisition',summary:'Automatisation qui détecte les paniers abandonnés sur Shopify et relance le client par SMS via Twilio.',summaryEn:'Automation that detects abandoned carts on Shopify and follows up with the client by SMS via Twilio.',tools:['Shopify','Twilio'],status:'published',featured:true,source:'comeup' },
  { title:'Facebook Leads → Systeme.io',titleEn:'Facebook Leads → Systeme.io',slug:'automatisation-facebook-leads-systeme-io',category:'Acquisition',categoryEn:'Acquisition',summary:'Automatisation qui récupère les leads Facebook, crée les contacts, applique les tags et les inscrit en campagne dans Systeme.io.',summaryEn:'Automation that retrieves Facebook leads, creates contacts, applies tags and enrolls them in a Systeme.io campaign.',tools:['Facebook Leads','Systeme.io'],status:'published',featured:true,source:'comeup' },
  { title:'ProRanker — classement automatique des candidatures',titleEn:'ProRanker — automatic candidate ranking',slug:'proranker-classement-candidatures-nlp',category:'Pilotage IA',categoryEn:'AI Piloting',summary:'Système de classement automatique des candidatures grâce au traitement du langage naturel (NLP).',summaryEn:'Automatic candidate ranking system powered by natural language processing (NLP).',tools:['NLP'],status:'published',featured:true,source:'comeup' },
  { title:'Automatisation CRM pilotée par agent IA',titleEn:'AI agent-driven CRM automation',slug:'automatisation-crm-agent-ia-n8n',category:'Pilotage IA',categoryEn:'AI Piloting',summary:'Agent IA branché sur n8n qui met à jour le CRM et déclenche les actions de suivi sans intervention manuelle.',summaryEn:'AI agent wired into n8n that updates the CRM and triggers follow-up actions without manual work.',tools:['n8n'],status:'published',featured:true,source:'comeup' },
]

// Avis réels extraits du profil ComeUp de NovatrixAI (comeup_extraction_finale.json).
// Aucune note n’a été capturée par l’extraction : le champ `rating` reste volontairement vide plutôt qu’inventé.
export const demoTestimonials: PublicTestimonial[] = [
  { name:'Donald Alban Petrus',role:'Président, DSAP – LDR Group',roleEn:'President, DSAP – LDR Group',text:'Je tiens à vous remercier sincèrement pour votre efficacité et votre réactivité face à une demande urgente. Votre travail est remarquable, réalisé avec sérieux, écoute du client et une véritable force de proposition.',textEn:'I sincerely want to thank you for your efficiency and responsiveness in handling an urgent request. Your work is remarkable, carried out with seriousness, attentiveness to the client, and real initiative.',source:'comeup',status:'published' },
  { name:'Francisco SC',role:'Client ComeUp',roleEn:'ComeUp client',text:'Excellent travail et très bonne communication. Un grand merci.',textEn:'Excellent work and very good communication. Many thanks.',source:'comeup',status:'published' },
  { name:'Robin Drezet',role:'Client ComeUp',roleEn:'ComeUp client',text:'Un travail d’une qualité exemplaire !',textEn:'Work of exemplary quality!',source:'comeup',status:'published' },
  { name:'WINGO',role:'Agence WingoAI',roleEn:'WingoAI Agency',text:'Merci à Dane pour son professionnalisme',textEn:'Thanks to Dane for his professionalism',source:'comeup',status:'published' },
  { name:'Thierry Phitoussi',role:'Client ComeUp',roleEn:'ComeUp client',text:'Très bon suivi et très bon travail. À recommander !',textEn:'Very good follow-up and very good work. Highly recommended!',source:'comeup',status:'published' },
]

export const demoArticles: PublicArticle[] = [
  { title:'Pourquoi votre acquisition se casse entre deux outils',titleEn:'Why your acquisition breaks between two tools',slug:'acquisition-cassee-entre-outils',excerpt:'Le vrai coût n’est pas toujours la campagne. Il se cache souvent dans le passage du lead au CRM, puis du CRM à la relance.',excerptEn:'The real cost isn’t always the campaign. It often hides in the handoff from lead to CRM, then from CRM to follow-up.',body:'## Le maillon invisible\n\nUne campagne peut produire des contacts sans produire de clients. La rupture arrive quand chaque outil fonctionne seul.\n\n## Cartographier avant d’automatiser\n\nSuivez un lead réel, du premier clic jusqu’à la décision. Chaque ressaisie, attente ou statut flou indique un maillon à reconstruire.\n\n## Relier le résultat\n\nUn système d’acquisition complet aligne les créatifs, les campagnes, le tunnel, le CRM, les relances et le closing autour d’une même donnée.',bodyEn:'## The invisible link\n\nA campaign can produce contacts without producing clients. The break happens when each tool works alone.\n\n## Map before automating\n\nFollow a real lead, from the first click to the decision. Every re-entry, delay or unclear status points to a link that needs rebuilding.\n\n## Connect the result\n\nA complete acquisition system aligns creatives, campaigns, funnel, CRM, follow-ups and closing around the same data.',category:'Acquisition',categoryEn:'Acquisition',tags:['CRM','Automatisation'],tagsEn:['CRM','Automation'],readingTime:4,readingTimeEn:4,status:'published',source:'manual',publishedAt:'2026-06-24T08:00:00.000Z' },
  { title:'Agents IA : où garder une validation humaine',titleEn:'AI agents: where to keep human validation',slug:'agents-ia-validation-humaine',excerpt:'L’autonomie utile ne consiste pas à tout laisser faire. Elle place la validation humaine exactement là où l’enjeu l’exige.',excerptEn:'Useful autonomy isn’t about letting everything run on its own. It places human validation exactly where the stakes require it.',body:'## Autonomie ne veut pas dire abandon\n\nUn agent peut préparer, analyser et exécuter. Sur les sujets juridiques, fiscaux ou financiers, une validation humaine doit rester explicite.\n\n## Trois niveaux simples\n\nObservation, proposition, puis exécution autorisée. Cette graduation rend le système fiable sans étouffer le gain de temps.',bodyEn:'## Autonomy doesn’t mean abandonment\n\nAn agent can prepare, analyze and execute. On legal, tax or financial matters, human validation needs to stay explicit.\n\n## Three simple levels\n\nObservation, proposal, then authorized execution. This grading makes the system reliable without smothering the time saved.',category:'Pilotage IA',categoryEn:'AI Piloting',tags:['Agents IA','Gouvernance'],tagsEn:['AI Agents','Governance'],readingTime:3,readingTimeEn:3,status:'published',source:'automation',publishedAt:'2026-06-20T08:00:00.000Z' },
  { title:'Le bon périmètre pour une première application métier',titleEn:'The right scope for a first business application',slug:'perimetre-premiere-application-metier',excerpt:'Commencer petit ne signifie pas construire au rabais. Cela signifie livrer une boucle métier complète et mesurable.',excerptEn:'Starting small doesn’t mean building cheap. It means shipping one complete, measurable business loop.',body:'## Une boucle complète\n\nChoisissez un utilisateur, une décision et un résultat. La première version doit couvrir cette boucle de bout en bout.\n\n## Ce qui attendra\n\nLes variantes rares et les raffinements visuels viennent après la validation du flux principal.',bodyEn:'## A complete loop\n\nChoose one user, one decision and one result. The first version must cover that loop end to end.\n\n## What can wait\n\nRare edge cases and visual polish come after the main flow is validated.',category:'Produit',categoryEn:'Product',tags:['Application','Cadrage'],tagsEn:['Application','Scoping'],readingTime:3,readingTimeEn:3,status:'published',source:'manual',publishedAt:'2026-06-16T08:00:00.000Z' },
]
