export type ResourceType = 'pdf' | 'video' | 'image' | 'template' | 'link'
export interface PublicResource { _id?:string;title:string;titleEn?:string;slug:string;description:string;descriptionEn?:string;type:ResourceType;sector:string;sectorEn?:string;fileKey?:string;coverImageKey?:string;gateFields?:string[];published:boolean;leadCount?:number;createdAt?:string }
export interface PublicArticle { _id?:string;title:string;titleEn?:string;slug:string;excerpt:string;excerptEn?:string;body:string;bodyEn?:string;coverImageKey?:string;category:string;categoryEn?:string;tags:string[];tagsEn?:string[];readingTime:number;readingTimeEn?:number;seo?:{metaTitle?:string;metaDescription?:string;ogImage?:string;canonical?:string};seoEn?:{metaTitle?:string;metaDescription?:string};status:'draft'|'published';source:'manual'|'automation';publishedAt?:string;createdAt?:string }

export interface ProjectQuote { text:string;author?:string }
export interface ProjectMetric { value:string;label:string }
export interface PublicProject { _id?:string;title:string;titleEn?:string;slug:string;category:string;categoryEn?:string;summary:string;summaryEn?:string;challenge?:string;challengeEn?:string;solution?:string;solutionEn?:string;features?:string[];featuresEn?:string[];quoteBefore?:ProjectQuote;quoteBeforeEn?:ProjectQuote;quoteAfter?:ProjectQuote;quoteAfterEn?:ProjectQuote;resultsMetrics?:ProjectMetric[];tools?:string[];deliveryDays?:number;coverImageKey?:string;status:'draft'|'published';featured?:boolean;sortOrder?:number;source?:'comeup'|'manual';createdAt?:string }

export interface PublicTestimonial { _id?:string;name:string;role?:string;roleEn?:string;text:string;textEn?:string;rating?:number;status:'pending'|'published'|'rejected';source:'comeup'|'site';reviewDate?:string;sortOrder?:number;createdAt?:string }
